# Generated by Django 5.2.6 on 2025-09-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_id', models.IntegerField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, max_length=200, null=True)),
                ('zone', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('party_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=100, null=True)),
                ('salesman', models.CharField(blank=True, max_length=200, null=True)),
                ('taxable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('voucher_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('realisable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('receive_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rmode', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_perc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('free_qty', models.IntegerField(blank=True, null=True)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('free_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
