# Generated by Django 5.2.6 on 2025-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_user', '0002_alter_exceldata_bill_type_alter_exceldata_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='district_dashboard',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='district_milk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='division',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='grouping_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='helper_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='kl_mt_outlets',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='new_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='new_sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='tn_mt_outlets',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='zone_mt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
