# Generated by Django 5.2.6 on 2025-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_user', '0003_exceldata_customer_name_exceldata_district_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='free_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
