# Generated by Django 5.2.6 on 2025-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_user', '0004_alter_exceldata_free_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='free_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
