from django.db import models

# Create your models here.
class ExcelData(models.Model):
    voucher_type = models.CharField(max_length=200, null=True, blank=True)
    sales_id = models.IntegerField(null=True, blank=True)
    state_name = models.CharField(max_length=200, null=True, blank=True)
    zone = models.CharField(max_length=200, null=True, blank=True)
    branch_name = models.CharField(max_length=200, null=True, blank=True)
    route = models.CharField(max_length=200, null=True, blank=True)
    party_name = models.CharField(max_length=200, null=True, blank=True)
    category_name = models.CharField(max_length=200, null=True, blank=True)
    payment_type = models.CharField(max_length=200, null=True, blank=True)
    created_date = models.DateField(null=True, blank=True)
    voucher_date = models.DateField(null=True, blank=True)
    voucher_no = models.CharField(max_length=200, null=True, blank=True)
    bill_type = models.CharField(max_length=200, null=True, blank=True)
    salesman = models.CharField(max_length=200, null=True, blank=True)
    taxable = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cgst = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    sgst = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    igst = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    voucher_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    discount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    realisable_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    receive_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    difference = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rmode = models.CharField(max_length=200, null=True, blank=True)
    group_name = models.CharField(max_length=200, null=True, blank=True)
    item_code = models.CharField(max_length=200, null=True, blank=True)
    tax_perc = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    qty = models.IntegerField(null=True, blank=True)
    free_qty = models.IntegerField(null=True, blank=True)
    total_amt = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    free_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rate = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    disc_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    helper_1 = models.CharField(max_length=200, null=True, blank=True)
    kl_mt_outlets = models.CharField(max_length=200, null=True, blank=True)
    tn_mt_outlets = models.CharField(max_length=200, null=True, blank=True)
    new_category = models.CharField(max_length=200, null=True, blank=True)
    new_sku = models.CharField(max_length=200, null=True, blank=True)
    division = models.CharField(max_length=200, null=True, blank=True)
    customer_name = models.CharField(max_length=200, null=True, blank=True)
    district_milk = models.CharField(max_length=200, null=True, blank=True)
    district_dashboard = models.CharField(max_length=200, null=True, blank=True)
    zone_mt = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):

        db_table = 'ExcelData'
